import discord
from discord.ext import commands
import asyncio
import random as r


class Misc(commands.Cog):
    """Miscellaneous Commands"""

    def __init__(self, client):
        self.client = client

    @commands.Cog.listener()
    async def on_member_join(self, member):
        print(f"Member {member.mention} has joined {member.guild.name}")

    @commands.command()
    async def ping(self, ctx):
        embed = discord.Embed(color=discord.Colour.from_rgb(255, 130, 53))
        embed.add_field(name="**Ping**", value=f":table_tennis: Pong! {self.client.latency * 1000} ms")
        await ctx.send(embed=embed)

    @commands.command(aliases=["murder"])
    async def kill(self, ctx, args=None):
        if not args:
            args = "someone"
        await ctx.send(f":dagger_knife: Sucessfully killed {args}")

    @commands.command()
    async def pong(self, ctx):
        embed = discord.Embed(color=discord.Colour.from_rgb(255, 130, 53))
        embed.add_field(name="**Pong**", value=f":table_tennis: Ping! {self.client.latency * 1000} ms")
        await ctx.send(embed=embed)

    @commands.command()
    async def fax(self, ctx, args=None):
        if args == "-s" or "--silent":
            await ctx.message.delete()
        await ctx.send("https://fax.pics")

    @commands.command()
    async def repeat(self, ctx, *, arg=None):
        if arg is None:
            await ctx.send(":x: Include something to repeat")
        else:
            await ctx.send(arg)

    @commands.command(name="8ball")
    async def eight_ball(self, ctx):
        await ctx.send(r.choice([
            "Yes", "My sources say yes", "You may count on it", "Most Likely", "Don't count on it.", "My reply is no.",
            "My sources say no.", "Outlook not so good.", "Very doubtful."
        ]))

    @commands.command(aliases=['hi'])
    async def hello(self, ctx):
        await ctx.send("Hello! :wave:")

    @commands.command(name="tryitandsee --silent", aliases=["tryit -s", "tias -s", "tryit --silent", "tias --silent"])
    async def tryitandseebutsilent(self, ctx):
        await ctx.message.delete
        await ctx.send("https://tryitands.ee")

    @commands.command(aliases=["tryit", "tias"])
    async def tryitandsee(self, ctx):
        await ctx.send("https://tryitands.ee")

    @commands.command()
    async def gruh(self, ctx):
        await ctx.send("Gruh moment")

    @commands.command(aliases=['ge', 'genembed', ])
    async def generate_embed(self, ctx, *, arg=None):
        embed = discord.Embed(color=discord.Colour.red())
        embed.add_field(name="Input", value=arg)
        embed.set_footer(icon_url=ctx.author.avatar_url, text=f"Generated by: {ctx.author.name}")

        await ctx.send(embed=embed)

    @commands.command(name="linux", aliases=["GNU/Linux", "g/l", ])
    async def linux(self, ctx):
        embed = discord.Embed(color=discord.Colour.from_rgb(255, 250, 250))
        embed.add_field(name="It's Linux, not GNU/LINUX", value="""No, Richard, it's 'Linux', not 'GNU/Linux'. 
		The most important contributions that the FSF made to Linux were the creation of the GPL and the GCC compiler. 
		Those are fine and inspired products. GCC is a monumental achievement and has earned you, RMS, and the Free Software Foundation countless kudos and much appreciation.""")
        embed.set_footer(icon_url=ctx.author.avatar_url, text=f"Requested by: {ctx.author.name}")

        await ctx.send(embed=embed)


    @commands.command()
    async def invite(self, ctx):
        embed = discord.Embed(color=discord.Colour.from_rgb(255, 150, 53))
        embed.add_field(name="Invite for Overseer",
                        value="[Invite](https://discord.com/oauth2/authorize?client_id=717215043724509275&scope=bot&permissions=8)")
        embed.set_footer(icon_url=ctx.author.avatar_url, text=f"Requested by: {ctx.author.name}")

        await ctx.send(embed=embed)



def setup(client):
    client.add_cog(Misc(client))


def teardown(client):
    client.remove_cog(Misc.__name__)
